#!/usr/bin/env bash

# GROKKING JAVA TOOL - Home made tool to build & run Grokking The Coding Interview study files

# CONSTANTS
## Change this to whatever value you'd like to package the files under, and make sure to update the all
##   of the .java files' "package XX;" header lines accordingly
DEFAULT_PACKAGE_NAME='com.cunningdj.grokJava'
## Change this to 1 if you want a printout of each step the tool is undergoing
VERBOSE=0
CLASSFILES_DIR=classes

## Moving into script directory
sd=`dirname $0`
cd $sd

# COMMANDS
function clean() {
  log "Cleaning $CLASSFILES_DIR/ ..."
  if [[ -d $CLASSFILES_DIR ]]; then
    rm -r $CLASSFILES_DIR
  fi
}

function build() {
  clean;
  log "Building class files in $CLASSFILES_DIR/ ..."
  mkdir $CLASSFILES_DIR
  javac -d $CLASSFILES_DIR ./*.java
}

function run() {
  classname=$1
  full_classname="$DEFAULT_PACKAGE_NAME.$classname"
  log "Running java class: $full_classname" 
  cd $CLASSFILES_DIR
  java "$full_classname"
}

function buildrun() {
  build;
  run $1
}

function log() {
  if [[ $VERBOSE -eq 1 ]]; then
    echo "$@";
  fi
}


# MAIN
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  cmd=$1
  if [[ "$cmd" == "run" ]]; then
    run "$2";
  elif [[ "$cmd" == "br" || "$cmd" == "buildrun" ]]; then
    buildrun "$2";
  elif [[ "$cmd" == "build" ]]; then
    build;
  elif [[ "$cmd" == "clean" ]]; then
    clean;
  else
    printf "USAGE: gtool CMD [...ARGS]\n\tCMD build|clean|run|br\n";
  fi
fi
