#!/usr/bin/env bash

# GROKKING JAVA TOOL - Home made tool to build & run Grokking The Coding Interview study files

# CONSTANTS
## Change this to whatever value you'd like to package the files under, and make sure to update the all
##   of the .java files' "package XX;" header lines accordingly
DEFAULT_PACKAGE_NAME='com.cunningdj.grokJava'
## Change this to 1 if you want a printout of each step the tool is undergoing
VERBOSE=0
CLASSFILES_DIR=classes

## Moving into script directory
sd=`dirname $0`
cd $sd

# COMMANDS
function clean() {
  log "Cleaning $CLASSFILES_DIR/ ..."
  if [[ -d $CLASSFILES_DIR ]]; then
    rm -r $CLASSFILES_DIR
  fi
}

function build() {
  clean;
  log "Building class files in $CLASSFILES_DIR/ ..."
  mkdir $CLASSFILES_DIR
  javac -d $CLASSFILES_DIR ./*.java
}

function run() {
  classname="$1"
  full_classname="$DEFAULT_PACKAGE_NAME.$classname"
  log "Running java class: $full_classname" 
  cd $CLASSFILES_DIR
  java "$full_classname"
}

function buildrun() {
  build;
  run "$1"
}

function log() {
  if [[ $VERBOSE -eq 1 ]]; then
    echo "$@";
  fi
}

function new() {
  classname="$1"
  javafile_name="$classname.java"
  if [[ "$classname" == "" ]]; then
    printf "USAGE: gtool new CLASSNAME\n\tCLASSNAME  Name of the java class.  A file [CLASSNAME].java will be made at the top level, with the 'package $DEFAULT_PACKAGE_NAME;' (set in gtool via DEFAULT_PACKAGE_NAME) already added at the top along with the basic class declaration.\n";
    exit 1;
  elif [[ -e "$javafile_name" ]]; then
    echo "ERROR: $javafile_name already exists!";
    exit 1;
  else
    # Create the file
    log "Creating new java file $javafile_name ..."
    touch $javafile_name;
    printf "package $DEFAULT_PACKAGE_NAME;\n\nclass $classname {\n" >> $javafile_name;
    printf "\tpublic static void main(String[] args) {\n\t\tTester tester = new Tester();\n" >> $javafile_name;
    printf "\t\tString testTitle=\"\";\n" >> $javafile_name;
    printf "\n\t\t// TEST CLASS METHODS HERE USING TESTER CLASS\n" >> $javafile_name;
    printf "\t}\n}\n" >> $javafile_name;
  fi
}


# MAIN
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  cmd=$1
  if [[ "$cmd" == "run" ]]; then
    run "$2";
  elif [[ "$cmd" == "br" || "$cmd" == "buildrun" ]]; then
    buildrun "$2";
  elif [[ "$cmd" == "build" ]]; then
    build;
  elif [[ "$cmd" == "clean" ]]; then
    clean;
  elif [[ "$cmd" == "new" ]]; then
    new "$2";
  else
    printf "USAGE: gtool CMD [...ARGS]\n\tCMD build|clean|run|br\n";
  fi
fi
